//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lottodo_webapi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltd_tbl_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ltd_tbl_plan()
        {
            this.ltd_tbl_chatgroups = new HashSet<ltd_tbl_chatgroups>();
        }
    
        public int ltd_PlanId { get; set; }
        public string ltd_UserId { get; set; }
        public string ltd_PlanName { get; set; }
        public string ltd_PlanDescription { get; set; }
        public int ltd_PlanTypeId { get; set; }
        public int ltd_PlanSubTypeId { get; set; }
        public System.DateTime ltd_PlanDateTime { get; set; }
        public string ltd_PlanLocation { get; set; }
        public int ltd_PlanGroupMaxSize { get; set; }
        public Nullable<int> ltd_PlanGroupSize { get; set; }
        public Nullable<int> ltd_PlanRadius { get; set; }
        public Nullable<int> ltd_PlanWaitTime { get; set; }
        public string ltd_PlanType { get; set; }
        public string ltd_PlanComments { get; set; }
        public string ltd_PlanSearchLocation { get; set; }
        public int ltd_PlanChatBoxId { get; set; }
        public bool ltd_Active { get; set; }
        public string ltd_AddInfo { get; set; }
        public System.DateTime ltd_CreatedDate { get; set; }
        public System.DateTime ltd_ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ltd_tbl_chatgroups> ltd_tbl_chatgroups { get; set; }
        public virtual ltd_tbl_chatgroups ltd_tbl_chatgroups1 { get; set; }
        public virtual ltd_tbl_userdetails ltd_tbl_userdetails { get; set; }
        public virtual ltd_tbl_plantypes ltd_tbl_plantypes { get; set; }
        public virtual ltd_tbl_plansubtypes ltd_tbl_plansubtypes { get; set; }
    }
}
