//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lottodo_webapi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltd_tbl_messages
    {
        public int ltd_MessageId { get; set; }
        public string ltd_UserId { get; set; }
        public int ltd_GroupId { get; set; }
        public string ltd_Message { get; set; }
        public string ltd_Status { get; set; }
        public System.DateTime ltd_SendDateTime { get; set; }
        public Nullable<System.DateTime> ltd_RecievedDateTime { get; set; }
        public Nullable<System.DateTime> ltd_SeenDateTime { get; set; }
        public string ltd_AddInfo { get; set; }
    
        public virtual ltd_tbl_chatgroups ltd_tbl_chatgroups { get; set; }
        public virtual ltd_tbl_userdetails ltd_tbl_userdetails { get; set; }
    }
}
